### PR TITLE
Fix example dataset

### LINKED ISSUE #527: Fix example data package `river_telemetry`
The paths to the resources of `river_telemetry` are not correct.

``` r
library(etn)
library(frictionless)

animals <-
  frictionless::read_resource(river_telemetry, "animals")
#> Error in `purrr::map_chr()`:
#> ℹ In index: 1.
#> Caused by error in `check_path()`:
#> ! Can't find file at
#>   '/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/etn/extdata/animals.csv'.
```

<sup>Created on 2026-04-07 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by sannegovaert**
- fix #527 
- related to #515

### CODE REVIEW

File: tests/testthat/test-example_dataset.R [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+  ),
+  {
+    expect_no_error(
+      frictionless::check_package(example_dataset(dataset = "2014_DEMER"))
+    )
+  }
+)
+
+test_that(
+  paste(
```
Comment (PietrH) [inline tests/testthat/test-example_dataset.R]: So far, I've always ignored the 80 lines rule for test titles. I think this is in line with our other packages.

File: R/example_dataset.R [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+#' directory = here::here("inst", "extdata", "2014_DEMER"))
+#' )`
+#' @param dataset Name of the example dataset to load. Defaults to the only
+#' available dataset "2014_DEMER".
+#' @return Frictionless data package of ETN dataset.
+#' @export
+#' @examples
+#' example_dataset()
+example_dataset <- function(dataset = "2014_DEMER") {
+  available_datasets <- c("2014_DEMER")
```
Comment (PietrH) [inline R/example_dataset.R:24]: Consider argument matching: https://rlang.r-lib.org/reference/arg_match.html, also possible in base.

File: tests/testthat/test-example_dataset.R (hunk 1 above)
Comment (peterdesmet) [reply tests/testthat/test-example_dataset.R]: I've corrected this to just wrap (cf. cli)

**Review by peterdesmet — APPROVED** [review]
Neat! Made some changes and tagged @sannegovaert to explain my reasoning.
